name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # hoặc master/main tùy vào nhánh chính của bạn
  workflow_dispatch:  # Cho phép chạy thủ công từ UI

# Đảm bảo chỉ một workflow chạy tại một thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: true  # Hủy các workflow đang chạy để tránh xung đột

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Gộp build và deploy thành một job duy nhất
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist  # hoặc thư mục build của bạn (build, out, etc.)
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3